### ISSUE TITLE
Missed cdn/webpack minify js

### ISSUE THREAD

**Issue by On1x** [GolosChain/golos-js#1]
#### Expected behavior

Link in readme for webpack minify js file on github/cdn script.

#### Actual behavior

There is simply no information about minify js file.

**Comment by pavq** [comment]
You can get minified version:
1. From [`npm.runkit.com/golos-js`](https://npm.runkit.com/golos-js).
<img width="480" alt="2017-08-02 11 11 06" src="https://user-images.githubusercontent.com/25533641/28863895-54463908-7773-11e7-9c4f-bd9bdcd26444.png">

2. From your local PC, just install package running `npm install golos-js`. After installation npm autorun [prepublish](https://github.com/GolosChain/golos-js/blob/master/package.json#L12) directive and build dists.

**Comment by On1x** [comment]
Ребята, дополните readme - любой начинающий разраб который откроет гитхаб стима и голоса просто выберет steem.js из-за наличия ссылки в шапке readme (там ссылка на CDN, но не суть).

**Comment by serejandmyself** [comment]
@pavelit @b1acksun дополните readme и закройте плиз

**Comment by t3ran13** [comment]
все еще актуально. 
в примерах линки на несуществующие файлы. 
как по мне можно и собирать в там где теги.

**Comment by On1x** [comment]
поднимаю тему. сделайте поддержку cdnjs

**Comment by epexa** [comment]
@On1x [как вариант ](https://github.com/GolosChain/golos-js/issues/16#issuecomment-353643296)

**Comment by t3ran13** [comment]
нужно добавить еще memo, почему он отсуствует в cdn?

**Comment by b1acksun** [comment]
@t3ran13 memo добавил https://github.com/GolosChain/golos-js/commit/cf873f785acb1d5dc20f4254c109caadc676d30d
