### ISSUE TITLE
подключение golos-js

### ISSUE THREAD

**Issue by votason** [GolosChain/golos-js#11]
На node js 

var golos = require("golos.min.js");

golos.config.set('websocket','ws://46.101.132.158:8092');
golos.config.set('address_prefix','GLS');
golos.config.set('chain_id','5876894a41e6361bde2e73278f07340f2eb8b41c2facd29099de9deef6cdb679');
все работает.

Когда подключаем 
<script src="<?=SITE_TEMPLATE_PATH . "/js/golos.min.js"?>"></script>

steem.config.set('websocket','ws://46.101.132.158:8092');
steem.config.set('address_prefix','GLS');
steem.config.set('chain_id','5876894a41e6361bde2e73278f07340f2eb8b41c2facd29099de9deef6cdb679');

соответственно var golos = require("golos.min.js"); не работает в клиенте, и процесс подключения к тесноту 
steem.config.set('websocket','ws://46.101.132.158:8092');
steem.config.set('address_prefix','GLS');
steem.config.set('chain_id','5876894a41e6361bde2e73278f07340f2eb8b41c2facd29099de9deef6cdb679');

 выдает ошибку : cannot red property 'set'

подскажите как в таком случае подключиться к тетнету, библиотека судя по всему по умолчанию сама к боевому подключается ??? Спасибо

**Comment by b1acksun** [comment]
Если необходимо использовать бибилиотеку в браузере для подключения к тестнету, то необходимо подключить ее с помощью тега `<script>` и она будет доступна через глобальную переменную `golos`
```
<script src="golos.min.js"></script>

<script> 
  golos.config.set('websocket','wss://ws.testnet.golos.io')
  golos.config.set('address_prefix','GLS')
  golos.config.set('chain_id','5876894a41e6361bde2e73278f07340f2eb8b41c2facd29099de9deef6cdb679')
</script>
```
