### ISSUE TITLE
"Invalid sequence tag" for signing key GLS1111111111111111111111111111111114T1Anm

### ISSUE THREAD

**Issue by Vik-BC** [GolosChain/golos-js#12]
Broadcasting any other keys works well, but
broadcasting a ```GLS1111111111111111111111111111111114T1Anm``` key by calling ```golos.broadcast.witnessUpdate``` 

causes an error: Invalid sequence tag

![image](https://user-images.githubusercontent.com/26347159/31782972-5a724b62-b505-11e7-94bd-5e15f0a3b6c8.png)

**Comment by On1x** [comment]
Up, need to fix it!

**Comment by Jolly-Pirate** [comment]
Any progress on this issue yet?

**Comment by asuleymanov** [comment]
Если я правильно понял описание из кода
```
block_signing_key The new block signing public key.  The empty string disables block production.
```
То для того чтобы остановить просто нужно указать там пустоту.

**Comment by asuleymanov** [comment]
Как я понимаю воз и ныне там.
Я подозреваю это из-за того что документация слабовата.
Пойдем пинать Core.

**Comment by asuleymanov** [comment]
Итак товарищи я нашел решение данной проблемы. По крайней мере на GO.

При получении данного ключа я делаю вот такую штуку.
```
if op.BlockSigningKey == "GLS1111111111111111111111111111111114T1Anm" {
		var dst []byte
		for i := 0; i < 33; i++ {
			dst = append(dst, 0)
		}
		enc.Encode(dst)
	} else {
		enc.EncodePubKey(op.BlockSigningKey)
	}
```

Попробую разъяснить.
Я создаю массив байт размером 33 и заполняю его нулями и именно это значение отправляю на сериализацию. А в JSON уходит непосредственно сам ключ.

Ну вот решение я нашел. Теперь дело за малым чтобы его у Вас в JS реализовали.

Если что непонятно готов разъяснить.

**Comment by Vik-BC** [comment]
https://github.com/steemit/steem-js/pull/390/commits/f051b0b714b98d560b7dbe38009396dc68d3d3e9

**Comment by b1acksun** [comment]
fixed in 0.7.2

**Comment by netuoso** [comment]
Man golos is on the ball. Might need to learn Russian and start contributing there more!
