### ISSUE TITLE
в getContent контент возвращается в markdown

### ISSUE THREAD

**Issue by epexa** [GolosChain/golos-js#14]
В [getContent](https://github.com/GolosChain/golos-js/tree/master/doc#get-content) в body возвращается markdown, а например в [getDiscussionsByBlog](getDiscussionsByBlog ) возвращается html.

**Comment by b1acksun** [comment]
С какими параметрами вызывается getContent  и getDiscussionsByBlog ?

**Comment by epexa** [comment]
@b1acksun 
```
golos.api.getContent(author, permlink, function(err, result) {
```

```
golos.api.getDiscussionsByBlog({
	select_tags: [tag],
	select_authors: [author],
	limit: 10
}, function(err, result) {
```

**Comment by b1acksun** [comment]
[getContent](https://gist.github.com/b1acksun/6aad5e6584dc6e714dbb2ee01cc35eca)
и 
[getDiscussionsByBlog](https://gist.github.com/b1acksun/5a9a199a0cf4d97e508d32d4add43535)
Здесь body содержит текст с разметкой html, также может содержать и markdown, все зависит в каком формате записали пост

**Comment by epexa** [comment]
@b1acksun а вот оно что значит... редактор видимо сначало написал в markdown, а потом переделал на html...
спасибо!
