### ISSUE TITLE
Deploy to CDN

### ISSUE THREAD

**Issue by chiliec** [GolosChain/golos-js#16]
Need to upload specific versions and latest from CDN. Perhaps there is some integrations with NPM.

**Comment by epexa** [comment]
# **You can use golos-js on CDN: [jsDelivr](https://cdn.jsdelivr.net/npm/golos-js/dist/golos.min.js) or [unpkg](https://unpkg.com/golos-js/dist/golos.min.js)!**

Example:
[https://cdn.jsdelivr.net/npm/golos-js@0.5.29/dist/golos.min.js](https://cdn.jsdelivr.net/npm/golos-js@0.5.29/dist/golos.min.js)
[https://unpkg.com/golos-js@0.5.29/dist/golos.min.js](https://unpkg.com/golos-js@0.5.29/dist/golos.min.js)
