### ISSUE TITLE
Please update API

### ISSUE THREAD

**Issue by gropox** [GolosChain/golos-js#17]
Please update the library for new API method get_delegated_vestings

https://github.com/GolosChain/golos/issues/307

**Comment by gropox** [comment]
any progress? Is there a process description? maybe I can do it my self for tests?

**Comment by b1acksun** [comment]
https://github.com/GolosChain/golos-js/commit/26e15aa3a78d68c221b856f6f6c5792f8542b73f#diff-addce624a1fc2f51fed990a507a1de42R182
