### ISSUE TITLE
Доработка и тестрироваение HF_0.17.0

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/golos-js#19]
@NickShtefan commented on [Thu Jan 18 2018](https://github.com/GolosChain/tolstoy/issues/578)

**Comment by b1acksun** [comment]
https://github.com/GolosChain/golos-js/commit/a6aa47b71b4246ecf1d3ceb7a549de8011f14a9f
https://github.com/GolosChain/golos-js/commit/b92fca26b7eb0028debdff8b679c543791393392
https://github.com/GolosChain/golos-js/commit/adffe9b56aa485badc9382296f98e07578eb0fd1
https://github.com/GolosChain/golos-js/commit/ba7729ed5bea9dc99278ff1107d7ac810e3f96e1

**Comment by b1acksun** [comment]
https://github.com/GolosChain/golos-js/commit/fbe1024c6c118982cf4389ff8c8d7e1b563889af
https://github.com/GolosChain/golos-js/commit/730a2eb14e9c840799ba834eb676bdcc7e69ffa7
