### ISSUE TITLE
Дополнить doc/README.md

### ISSUE THREAD

**Issue by b1acksun** [GolosChain/golos-js#20]
Описание и примеры
- [x] 1. Get Followers
- [x] 2. Get Following
- [x] 3. Get Follow Count
- [x] 4. Transfer
- [ ] 5. Vote
- [x] 6. Get Ticker
- [x] 7. Account Create
- [x] 8. Login
- [x] 9. Comment
- [x] 10. Get Discussions By Blog
- [x] 11. Get Discussions By Trending
- [x] 12. Get Content
- [x] 13. Get Content Replies

**Comment by html-code** [comment]
BTW, your https://github.com/GolosChain/golos-js/blob/master/README.md links are broken, can't get docs with them
