### ISSUE TITLE
Не отрабатывает changeRecoveryAccount

### ISSUE THREAD

**Issue by On1x** [GolosChain/golos-js#3]
Привет, пытаюсь поменять recovery_account для юзера cryptostorm (создан юзером goldvoice) - на on1x.

Код:
```
var user={login:'testuser',password:'somepass'};
golos.broadcast.changeRecoveryAccount(golos.auth.toWif(user.login,user.password,'owner'),user.login,'on1x','', function(err, result) {
	console.log(err, result);
});
```

Дебаг (проходит все отлично):
![](http://on1x.com/screen/08-2017/1981-251f.png)

Но recovery_account не меняется, проверяю через API http://golostools.ru/explorer/#method=get_accounts&params=[["cryptostorm"]]

**Comment by b1acksun** [comment]
https://github.com/GolosChain/golos/blob/master/libraries/protocol/include/steemit/protocol/steem_operations.hpp#L892

Существует временная задержка:

An account can change their recovery account at any time with a 30 day delay. This delay is to prevent an attacker from changing the recovery account to a malicious account during an attack. These 30 days match the 30 days that an owner authority is valid for recovery purposes.

**Comment by On1x** [comment]
То-есть владелец сменится через 30 дней автоматически после запроса? Или нужно будет повторить запрос? Можно ссылку на код, где проверка на эти 30 дней происходит? В коде по ссылке никаких подобных условий нет (они описаны только в комментариях).

**Comment by b1acksun** [comment]
Здесь устанавливается временная задержка в 30 дней https://github.com/GolosChain/golos/blob/master/libraries/chain/steem_evaluator.cpp#L1981 здесь идет проверка https://github.com/GolosChain/golos/blob/master/libraries/chain/database.cpp#L2598

**Comment by b1acksun** [comment]
По истечению 30 дней, recovery_account изменился на on1x
