### ISSUE TITLE
Не получается создать юзера

### ISSUE THREAD

**Issue by votason** [GolosChain/golos-js#4]
Побсобите, в чем может быть косяк?

Подключился к ТЕСТНЕТ, данные сети, get_config():

> null  { STEEMIT_BUILD_TESTNET: true,
  GRAPHENE_CURRENT_DB_VERSION: 'GPH2.4',
  SBD_SYMBOL: 1195525891,
  STEEMIT_100_PERCENT: 10000,
  STEEMIT_1_PERCENT: 100,
  STEEMIT_ADDRESS_PREFIX: 'GLS',
  STEEMIT_APR_PERCENT_MULTIPLY_PER_BLOCK: '102035135585887',
  STEEMIT_APR_PERCENT_MULTIPLY_PER_HOUR: '119577151364285',
  STEEMIT_APR_PERCENT_MULTIPLY_PER_ROUND: '133921203762304',
  STEEMIT_APR_PERCENT_SHIFT_PER_BLOCK: 87,
  STEEMIT_APR_PERCENT_SHIFT_PER_HOUR: 77,
  STEEMIT_APR_PERCENT_SHIFT_PER_ROUND: 83,
  STEEMIT_BANDWIDTH_AVERAGE_WINDOW_SECONDS: 604800,
  STEEMIT_BANDWIDTH_PRECISION: 1000000,
  STEEMIT_BLOCKCHAIN_PRECISION: 1000,
  STEEMIT_BLOCKCHAIN_PRECISION_DIGITS: 3,
  STEEMIT_BLOCKCHAIN_HARDFORK_VERSION: '0.17.0',
  STEEMIT_BLOCKCHAIN_VERSION: '0.17.0',
  STEEMIT_BLOCK_INTERVAL: 3,
  STEEMIT_BLOCKS_PER_DAY: 28800,
  STEEMIT_BLOCKS_PER_HOUR: 1200,
  STEEMIT_BLOCKS_PER_YEAR: 10512000,
  STEEMIT_CASHOUT_WINDOW_SECONDS: 3600,
  STEEMIT_CHAIN_ID: '5876894a41e6361bde2e73278f07340f2eb8b41c2facd29099de9deef6cdb679',
  STEEMIT_CONTENT_APR_PERCENT: 5813,
  STEEMIT_CONVERSION_DELAY: '302400000000',
  STEEMIT_CURATE_APR_PERCENT: 1937,
  STEEMIT_DEFAULT_SBD_INTEREST_RATE: 1000,
  STEEMIT_FEED_HISTORY_WINDOW: 84,
  STEEMIT_FEED_INTERVAL_BLOCKS: 20,
  STEEMIT_FREE_TRANSACTIONS_WITH_NEW_ACCOUNT: 100,
  STEEMIT_GENESIS_TIME: '2016-10-18T11:00:00',
  STEEMIT_HARDFORK_REQUIRED_WITNESSES: 1,
  STEEMIT_INIT_MINER_NAME: 'cyberfounder',
  STEEMIT_INIT_PUBLIC_KEY_STR: 'GLS58g5rWYS3XFTuGDSxLVwiBiPLoAyCZgn6aB9Ueh8Hj5qwQA3r6',
  STEEMIT_INIT_SUPPLY: '43306176000',
  STEEMIT_INIT_TIME: '1970-01-01T00:00:00',
  STEEMIT_IRREVERSIBLE_THRESHOLD: 7500,
  STEEMIT_LIQUIDITY_APR_PERCENT: 750,
  STEEMIT_LIQUIDITY_REWARD_BLOCKS: 1200,
  STEEMIT_LIQUIDITY_REWARD_PERIOD_SEC: 3600,
  STEEMIT_LIQUIDITY_TIMEOUT_SEC: '604800000000',
  STEEMIT_MAX_ACCOUNT_NAME_LENGTH: 16,
  STEEMIT_MAX_ACCOUNT_WITNESS_VOTES: 30,
  STEEMIT_MAX_ASSET_WHITELIST_AUTHORITIES: 10,
  STEEMIT_MAX_AUTHORITY_MEMBERSHIP: 10,
  STEEMIT_MAX_BLOCK_SIZE: 393216000,
  STEEMIT_MAX_CASHOUT_WINDOW_SECONDS: 7200,
  STEEMIT_MAX_COMMENT_DEPTH: 65535,
  STEEMIT_MAX_FEED_AGE: '604800000000',
  STEEMIT_MAX_INSTANCE_ID: '281474976710655',
  STEEMIT_MAX_MEMO_SIZE: 2048,
  STEEMIT_MAX_WITNESSES: 3,
  STEEMIT_MAX_MINER_WITNESSES: 1,
  STEEMIT_MAX_PROXY_RECURSION_DEPTH: 4,
  STEEMIT_MAX_RATION_DECAY_RATE: 1000000,
  STEEMIT_MAX_RESERVE_RATIO: 20000,
  STEEMIT_MAX_RUNNER_WITNESSES: 1,
  STEEMIT_MAX_SHARE_SUPPLY: '1000000000000000',
  STEEMIT_MAX_SIG_CHECK_DEPTH: 2,
  STEEMIT_MAX_TIME_UNTIL_EXPIRATION: 3600,
  STEEMIT_MAX_TRANSACTION_SIZE: 65536,
  STEEMIT_MAX_UNDO_HISTORY: 10000,
  STEEMIT_MAX_URL_LENGTH: 127,
  STEEMIT_MAX_VOTE_CHANGES: 5,
  STEEMIT_MAX_VOTED_WITNESSES: 1,
  STEEMIT_MAX_WITHDRAW_ROUTES: 10,
  STEEMIT_MAX_WITNESS_URL_LENGTH: 2048,
  STEEMIT_MIN_ACCOUNT_CREATION_FEE: 0,
  STEEMIT_MIN_ACCOUNT_NAME_LENGTH: 3,
  STEEMIT_MIN_BLOCK_SIZE_LIMIT: 65536,
  STEEMIT_MIN_CONTENT_REWARD: '1.500 GOLOS',
  STEEMIT_MIN_CURATE_REWARD: '0.500 GOLOS',
  STEEMIT_MINER_ACCOUNT: 'miners',
  STEEMIT_MINER_PAY_PERCENT: 100,
  STEEMIT_MIN_FEEDS: 1,
  STEEMIT_MINING_REWARD: '0.666 GOLOS',
  STEEMIT_MINING_TIME: '2016-01-01T00:00:00',
  STEEMIT_MIN_LIQUIDITY_REWARD: '1200.000 GOLOS',
  STEEMIT_MIN_LIQUIDITY_REWARD_PERIOD_SEC: 60000000,
  STEEMIT_MIN_PAYOUT_SBD: '0.020 GBG',
  STEEMIT_MIN_POW_REWARD: '0.666 GOLOS',
  STEEMIT_MIN_PRODUCER_REWARD: '0.666 GOLOS',
  STEEMIT_MIN_RATION: 100000,
  STEEMIT_MIN_TRANSACTION_EXPIRATION_LIMIT: 15,
  STEEMIT_MIN_TRANSACTION_SIZE_LIMIT: 1024,
  STEEMIT_MIN_UNDO_HISTORY: 10,
  STEEMIT_NULL_ACCOUNT: 'null',
  STEEMIT_NUM_INIT_MINERS: 1,
  STEEMIT_POW_APR_PERCENT: 750,
  STEEMIT_PRODUCER_APR_PERCENT: 750,
  STEEMIT_PROXY_TO_SELF_ACCOUNT: '',
  STEEMIT_SBD_INTEREST_COMPOUND_INTERVAL_SEC: 2592000,
  STEEMIT_SECONDS_PER_YEAR: 31536000,
  STEEMIT_REVERSE_AUCTION_WINDOW_SECONDS: 1800,
  STEEMIT_START_MINER_VOTING_BLOCK: 200,
  STEEMIT_START_VESTING_BLOCK: 56,
  STEEMIT_SYMBOL: 'GOLOS',
  STEEMIT_TEMP_ACCOUNT: 'temp',
  STEEMIT_UPVOTE_LOCKOUT: 60000000,
  STEEMIT_VESTING_WITHDRAW_INTERVALS: 20,
  STEEMIT_VESTING_WITHDRAW_INTERVAL_SECONDS: 604800,
  STEEMIT_VOTE_CHANGE_LOCKOUT_PERIOD: 600,
  STEEMIT_VOTE_REGENERATION_SECONDS: 432000,
  STEEM_SYMBOL: '91600047785731',
  VESTS_SYMBOL: '91621639407366',
  BLOCKCHAIN_NAME: 'GOLOSTEST' }

/golos.api.getActiveWitnesses(function(err, result) {
  console.log(err, result);
});/

> null

 [ 'cyberfounder', '', '' ]

/golos.api.getChainProperties(function(err, result) {
  console.log(err, result);
});/ 

> null

 { account_creation_fee: '0.000 GOLOS',
  maximum_block_size: 131072,
  sbd_interest_rate: 1000 }

создание юзера:

var userName = 'vtsn';
var password = 'aercbz';
var authTypes = ['posting', 'active', 'owner', 'memo'];
var keys = golos.auth.generateKeys(userName, password , authTypes);

var creator = 'cyberfounder'
var wif = '5JVFFWRLwz6JoP9kguuRFfytToGU6cLgBVTL9t6NB3D3BQLbUBS'; //private active key
var fee = '0.000 GOLOS';
var creator = 'cyberfounder';
var newAccountName = userName;

var owner = {
        "weight_threshold": 1,
        "account_auths": [],
        "key_auths": [
          [keys.owner, 1]
        ]
      };
var active = {
        "weight_threshold": 1,
        "account_auths": [],
        "key_auths": [
          [keys.active, 1]
        ]
      };
var posting = {
        "weight_threshold": 1,
        "account_auths": [],
        "key_auths": [
          [keys.posting, 1]
        ]
      };
var memoKey = keys.memo;
var jsonMetadata = '';

golos.broadcast.accountCreate(wif, fee, creator, newAccountName,
        owner, active, posting, memoKey, jsonMetadata, function(err, result) {
  console.log(err, result);
});

вывод скрипта:

> {

 Error: 3010000 tx_missing_active_auth: missing required active authority
Missing Active Authority cyberfounder
    {"id":"cyberfounder","auth":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS58g5rWYS3XFTuGDSxLVwiBiPLoAyCZgn6aB9Ueh8Hj5qwQA3r6",1]]},"owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS58g5rWYS3XFTuGDSxLVwiBiPLoAyCZgn6aB9Ueh8Hj5qwQA3r6",1]]}}
    th_a  transaction.cpp:149 verify_authority

    {"ops":[["account_create",{"fee":"0.000 GOLOS","creator":"cyberfounder","new_account_name":"vtsn","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS8DUuUETweg3f3YN6VypNKFTcxZ9uFqxVi6x2TuGaPYg9eJF6VZ",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS74vRVnybySiuya1d3JBeUGEw6aw4pWwcUf5aaxajj4X2EJss2G",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS5W9jtsqhZUbvobKcpng8jicvwUBnDxjZjUyJ355GXDC7J75J9J",1]]},"memo_key":"GLS7C5ufZagDvWRJg9XTGF51VrENfqpRRFzhoUjnyFUc9nptGoMpf","json_metadata":""}]],"sigs":["GLS8kHe83t5oU1eaBuGL1HhxWPaSchJ3pj7D92a6KpJVVqxrq5piM"]}
    th_a  transaction.cpp:164 verify_authority

    {"*this":{"ref_block_num":21133,"ref_block_prefix":3056859848,"expiration":"2017-08-21T06:38:48","operations":[["account_create",{"fee":"0.000 GOLOS","creator":"cyberfounder","new_account_name":"vtsn","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS8DUuUETweg3f3YN6VypNKFTcxZ9uFqxVi6x2TuGaPYg9eJF6VZ",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS74vRVnybySiuya1d3JBeUGEw6aw4pWwcUf5aaxajj4X2EJss2G",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS5W9jtsqhZUbvobKcpng8jicvwUBnDxjZjUyJ355GXDC7J75J9J",1]]},"memo_key":"GLS7C5ufZagDvWRJg9XTGF51VrENfqpRRFzhoUjnyFUc9nptGoMpf","json_metadata":""}]],"extensions":[],"signatures":["2017cc34a168cf669dbe916c6068f1aaecdc31248def2822565758538f9b8636b27fde91500f04471d85239c277e69c3fed9496e5c7c3144251ee8626f911ea065"]}}
    th_a  transaction.cpp:287 verify_authority

    {"trx":{"ref_block_num":21133,"ref_block_prefix":3056859848,"expiration":"2017-08-21T06:38:48","operations":[["account_create",{"fee":"0.000 GOLOS","creator":"cyberfounder","new_account_name":"vtsn","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS8DUuUETweg3f3YN6VypNKFTcxZ9uFqxVi6x2TuGaPYg9eJF6VZ",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS74vRVnybySiuya1d3JBeUGEw6aw4pWwcUf5aaxajj4X2EJss2G",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS5W9jtsqhZUbvobKcpng8jicvwUBnDxjZjUyJ355GXDC7J75J9J",1]]},"memo_key":"GLS7C5ufZagDvWRJg9XTGF51VrENfqpRRFzhoUjnyFUc9nptGoMpf","json_metadata":""}]],"extensions":[],"signatures":["2017cc34a168cf669dbe916c6068f1aaecdc31248def2822565758538f9b8636b27fde91500f04471d85239c277e69c3fed9496e5c7c3144251ee8626f911ea065"]}}
    th_a  database.cpp:2995 _apply_transaction

    {"trx":{"ref_block_num":21133,"ref_block_prefix":3056859848,"expiration":"2017-08-21T06:38:48","operations":[["account_create",{"fee":"0.000 GOLOS","creator":"cyberfounder","new_account_name":"vtsn","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS8DUuUETweg3f3YN6VypNKFTcxZ9uFqxVi6x2TuGaPYg9eJF6VZ",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS74vRVnybySiuya1d3JBeUGEw6aw4pWwcUf5aaxajj4X2EJss2G",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS5W9jtsqhZUbvobKcpng8jicvwUBnDxjZjUyJ355GXDC7J75J9J",1]]},"memo_key":"GLS7C5ufZagDvWRJg9XTGF51VrENfqpRRFzhoUjnyFUc9nptGoMpf","json_metadata":""}]],"extensions":[],"signatures":["2017cc34a168cf669dbe916c6068f1aaecdc31248def2822565758538f9b8636b27fde91500f04471d85239c277e69c3fed9496e5c7c3144251ee8626f911ea065"]}}
    th_a  database.cpp:825 push_transaction

    {"call.method":"call","call.params":[3,"broadcast_transaction_with_callback",[null,{"ref_block_num":21133,"ref_block_prefix":3056859848,"expiration":"2017-08-21T06:38:48","operations":[["account_create",{"fee":"0.000 GOLOS","creator":"cyberfounder","new_account_name":"vtsn","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS8DUuUETweg3f3YN6VypNKFTcxZ9uFqxVi6x2TuGaPYg9eJF6VZ",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS74vRVnybySiuya1d3JBeUGEw6aw4pWwcUf5aaxajj4X2EJss2G",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS5W9jtsqhZUbvobKcpng8jicvwUBnDxjZjUyJ355GXDC7J75J9J",1]]},"memo_key":"GLS7C5ufZagDvWRJg9XTGF51VrENfqpRRFzhoUjnyFUc9nptGoMpf","json_metadata":""}]],"extensions":[],"signatures":["2017cc34a168cf669dbe916c6068f1aaecdc31248def2822565758538f9b8636b27fde91500f04471d85239c277e69c3fed9496e5c7c3144251ee8626f911ea065"]}]]}
    th_a  websocket_api.cpp:124 on_message (see err.payload for the full error payload)
    at Golos.onMessage (/root/node_modules/golos-js/lib/api/index.js:234:19)
    at WebSocket.<anonymous> (/root/node_modules/golos-js/lib/api/index.js:150:18)
    at WebSocket.onMessage (/root/node_modules/ws/lib/WebSocket.js:442:14)
    at emitTwo (events.js:125:13)
    at WebSocket.emit (events.js:213:7)
    at Receiver.ontext (/root/node_modules/ws/lib/WebSocket.js:841:10)
    at /root/node_modules/ws/lib/Receiver.js:536:18
    at Receiver.applyExtensions (/root/node_modules/ws/lib/Receiver.js:371:5)
    at /root/node_modules/ws/lib/Receiver.js:508:14
    at Receiver.flush (/root/node_modules/ws/lib/Receiver.js:347:3)
    at Receiver.finish (/root/node_modules/ws/lib/Receiver.js:541:12)
    at Receiver.expectHandler (/root/node_modules/ws/lib/Receiver.js:499:31)
    at Receiver.add (/root/node_modules/ws/lib/Receiver.js:103:24)
    at Socket.realHandler (/root/node_modules/ws/lib/WebSocket.js:825:20)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
  cause:
   { Error: 3010000 tx_missing_active_auth: missing required active authority
   Missing Active Authority cyberfounder
       {"id":"cyberfounder","auth":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS58g5rWYS3XFTuGDSxLVwiBiPLoAyCZgn6aB9Ueh8Hj5qwQA3r6",1]]},"owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS58g5rWYS3XFTuGDSxLVwiBiPLoAyCZgn6aB9Ueh8Hj5qwQA3r6",1]]}}
       th_a  transaction.cpp:149 verify_authority

       {"ops":[["account_create",{"fee":"0.000 GOLOS","creator":"cyberfounder","new_account_name":"vtsn","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS8DUuUETweg3f3YN6VypNKFTcxZ9uFqxVi6x2TuGaPYg9eJF6VZ",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS74vRVnybySiuya1d3JBeUGEw6aw4pWwcUf5aaxajj4X2EJss2G",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS5W9jtsqhZUbvobKcpng8jicvwUBnDxjZjUyJ355GXDC7J75J9J",1]]},"memo_key":"GLS7C5ufZagDvWRJg9XTGF51VrENfqpRRFzhoUjnyFUc9nptGoMpf","json_metadata":""}]],"sigs":["GLS8kHe83t5oU1eaBuGL1HhxWPaSchJ3pj7D92a6KpJVVqxrq5piM"]}
       th_a  transaction.cpp:164 verify_authority

       {"*this":{"ref_block_num":21133,"ref_block_prefix":3056859848,"expiration":"2017-08-21T06:38:48","operations":[["account_create",{"fee":"0.000 GOLOS","creator":"cyberfounder","new_account_name":"vtsn","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS8DUuUETweg3f3YN6VypNKFTcxZ9uFqxVi6x2TuGaPYg9eJF6VZ",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS74vRVnybySiuya1d3JBeUGEw6aw4pWwcUf5aaxajj4X2EJss2G",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS5W9jtsqhZUbvobKcpng8jicvwUBnDxjZjUyJ355GXDC7J75J9J",1]]},"memo_key":"GLS7C5ufZagDvWRJg9XTGF51VrENfqpRRFzhoUjnyFUc9nptGoMpf","json_metadata":""}]],"extensions":[],"signatures":["2017cc34a168cf669dbe916c6068f1aaecdc31248def2822565758538f9b8636b27fde91500f04471d85239c277e69c3fed9496e5c7c3144251ee8626f911ea065"]}}
       th_a  transaction.cpp:287 verify_authority

       {"trx":{"ref_block_num":21133,"ref_block_prefix":3056859848,"expiration":"2017-08-21T06:38:48","operations":[["account_create",{"fee":"0.000 GOLOS","creator":"cyberfounder","new_account_name":"vtsn","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS8DUuUETweg3f3YN6VypNKFTcxZ9uFqxVi6x2TuGaPYg9eJF6VZ",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS74vRVnybySiuya1d3JBeUGEw6aw4pWwcUf5aaxajj4X2EJss2G",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS5W9jtsqhZUbvobKcpng8jicvwUBnDxjZjUyJ355GXDC7J75J9J",1]]},"memo_key":"GLS7C5ufZagDvWRJg9XTGF51VrENfqpRRFzhoUjnyFUc9nptGoMpf","json_metadata":""}]],"extensions":[],"signatures":["2017cc34a168cf669dbe916c6068f1aaecdc31248def2822565758538f9b8636b27fde91500f04471d85239c277e69c3fed9496e5c7c3144251ee8626f911ea065"]}}
       th_a  database.cpp:2995 _apply_transaction

       {"trx":{"ref_block_num":21133,"ref_block_prefix":3056859848,"expiration":"2017-08-21T06:38:48","operations":[["account_create",{"fee":"0.000 GOLOS","creator":"cyberfounder","new_account_name":"vtsn","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS8DUuUETweg3f3YN6VypNKFTcxZ9uFqxVi6x2TuGaPYg9eJF6VZ",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS74vRVnybySiuya1d3JBeUGEw6aw4pWwcUf5aaxajj4X2EJss2G",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS5W9jtsqhZUbvobKcpng8jicvwUBnDxjZjUyJ355GXDC7J75J9J",1]]},"memo_key":"GLS7C5ufZagDvWRJg9XTGF51VrENfqpRRFzhoUjnyFUc9nptGoMpf","json_metadata":""}]],"extensions":[],"signatures":["2017cc34a168cf669dbe916c6068f1aaecdc31248def2822565758538f9b8636b27fde91500f04471d85239c277e69c3fed9496e5c7c3144251ee8626f911ea065"]}}
       th_a  database.cpp:825 push_transaction

       {"call.method":"call","call.params":[3,"broadcast_transaction_with_callback",[null,{"ref_block_num":21133,"ref_block_prefix":3056859848,"expiration":"2017-08-21T06:38:48","operations":[["account_create",{"fee":"0.000 GOLOS","creator":"cyberfounder","new_account_name":"vtsn","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS8DUuUETweg3f3YN6VypNKFTcxZ9uFqxVi6x2TuGaPYg9eJF6VZ",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS74vRVnybySiuya1d3JBeUGEw6aw4pWwcUf5aaxajj4X2EJss2G",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS5W9jtsqhZUbvobKcpng8jicvwUBnDxjZjUyJ355GXDC7J75J9J",1]]},"memo_key":"GLS7C5ufZagDvWRJg9XTGF51VrENfqpRRFzhoUjnyFUc9nptGoMpf","json_metadata":""}]],"extensions":[],"signatures":["2017cc34a168cf669dbe916c6068f1aaecdc31248def2822565758538f9b8636b27fde91500f04471d85239c277e69c3fed9496e5c7c3144251ee8626f911ea065"]}]]}
       th_a  websocket_api.cpp:124 on_message (see err.payload for the full error payload)
       at Golos.onMessage (/root/node_modules/golos-js/lib/api/index.js:234:19)
       at WebSocket.<anonymous> (/root/node_modules/golos-js/lib/api/index.js:150:18)
       at WebSocket.onMessage (/root/node_modules/ws/lib/WebSocket.js:442:14)
       at emitTwo (events.js:125:13)
       at WebSocket.emit (events.js:213:7)
       at Receiver.ontext (/root/node_modules/ws/lib/WebSocket.js:841:10)
       at /root/node_modules/ws/lib/Receiver.js:536:18
       at Receiver.applyExtensions (/root/node_modules/ws/lib/Receiver.js:371:5)
       at /root/node_modules/ws/lib/Receiver.js:508:14
       at Receiver.flush (/root/node_modules/ws/lib/Receiver.js:347:3)
       at Receiver.finish (/root/node_modules/ws/lib/Receiver.js:541:12)
       at Receiver.expectHandler (/root/node_modules/ws/lib/Receiver.js:499:31)
       at Receiver.add (/root/node_modules/ws/lib/Receiver.js:103:24)
       at Socket.realHandler (/root/node_modules/ws/lib/WebSocket.js:825:20)
       at emitOne (events.js:115:13)
       at Socket.emit (events.js:210:7) payload: { id: 8, error: [Object] } },
  isOperational: true,
  payload:
   { id: 8,
     error:
      { code: 1,
        message: '3010000 tx_missing_active_auth: missing required active authority\nMissing Active Authority cyberfounder\n    {"id":"cyberfounder","auth":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS58g5rWYS3XFTuGDSxLVwiBiPLoAyCZgn6aB9Ueh8Hj5qwQA3r6",1]]},"owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS58g5rWYS3XFTuGDSxLVwiBiPLoAyCZgn6aB9Ueh8Hj5qwQA3r6",1]]}}\n    th_a  transaction.cpp:149 verify_authority\n\n    {"ops":[["account_create",{"fee":"0.000 GOLOS","creator":"cyberfounder","new_account_name":"vtsn","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS8DUuUETweg3f3YN6VypNKFTcxZ9uFqxVi6x2TuGaPYg9eJF6VZ",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS74vRVnybySiuya1d3JBeUGEw6aw4pWwcUf5aaxajj4X2EJss2G",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS5W9jtsqhZUbvobKcpng8jicvwUBnDxjZjUyJ355GXDC7J75J9J",1]]},"memo_key":"GLS7C5ufZagDvWRJg9XTGF51VrENfqpRRFzhoUjnyFUc9nptGoMpf","json_metadata":""}]],"sigs":["GLS8kHe83t5oU1eaBuGL1HhxWPaSchJ3pj7D92a6KpJVVqxrq5piM"]}\n    th_a  transaction.cpp:164 verify_authority\n\n    {"*this":{"ref_block_num":21133,"ref_block_prefix":3056859848,"expiration":"2017-08-21T06:38:48","operations":[["account_create",{"fee":"0.000 GOLOS","creator":"cyberfounder","new_account_name":"vtsn","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS8DUuUETweg3f3YN6VypNKFTcxZ9uFqxVi6x2TuGaPYg9eJF6VZ",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS74vRVnybySiuya1d3JBeUGEw6aw4pWwcUf5aaxajj4X2EJss2G",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS5W9jtsqhZUbvobKcpng8jicvwUBnDxjZjUyJ355GXDC7J75J9J",1]]},"memo_key":"GLS7C5ufZagDvWRJg9XTGF51VrENfqpRRFzhoUjnyFUc9nptGoMpf","json_metadata":""}]],"extensions":[],"signatures":["2017cc34a168cf669dbe916c6068f1aaecdc31248def2822565758538f9b8636b27fde91500f04471d85239c277e69c3fed9496e5c7c3144251ee8626f911ea065"]}}\n    th_a  transaction.cpp:287 verify_authority\n\n    {"trx":{"ref_block_num":21133,"ref_block_prefix":3056859848,"expiration":"2017-08-21T06:38:48","operations":[["account_create",{"fee":"0.000 GOLOS","creator":"cyberfounder","new_account_name":"vtsn","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS8DUuUETweg3f3YN6VypNKFTcxZ9uFqxVi6x2TuGaPYg9eJF6VZ",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS74vRVnybySiuya1d3JBeUGEw6aw4pWwcUf5aaxajj4X2EJss2G",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS5W9jtsqhZUbvobKcpng8jicvwUBnDxjZjUyJ355GXDC7J75J9J",1]]},"memo_key":"GLS7C5ufZagDvWRJg9XTGF51VrENfqpRRFzhoUjnyFUc9nptGoMpf","json_metadata":""}]],"extensions":[],"signatures":["2017cc34a168cf669dbe916c6068f1aaecdc31248def2822565758538f9b8636b27fde91500f04471d85239c277e69c3fed9496e5c7c3144251ee8626f911ea065"]}}\n    th_a  database.cpp:2995 _apply_transaction\n\n    {"trx":{"ref_block_num":21133,"ref_block_prefix":3056859848,"expiration":"2017-08-21T06:38:48","operations":[["account_create",{"fee":"0.000 GOLOS","creator":"cyberfounder","new_account_name":"vtsn","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS8DUuUETweg3f3YN6VypNKFTcxZ9uFqxVi6x2TuGaPYg9eJF6VZ",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS74vRVnybySiuya1d3JBeUGEw6aw4pWwcUf5aaxajj4X2EJss2G",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS5W9jtsqhZUbvobKcpng8jicvwUBnDxjZjUyJ355GXDC7J75J9J",1]]},"memo_key":"GLS7C5ufZagDvWRJg9XTGF51VrENfqpRRFzhoUjnyFUc9nptGoMpf","json_metadata":""}]],"extensions":[],"signatures":["2017cc34a168cf669dbe916c6068f1aaecdc31248def2822565758538f9b8636b27fde91500f04471d85239c277e69c3fed9496e5c7c3144251ee8626f911ea065"]}}\n    th_a  database.cpp:825 push_transaction\n\n    {"call.method":"call","call.params":[3,"broadcast_transaction_with_callback",[null,{"ref_block_num":21133,"ref_block_prefix":3056859848,"expiration":"2017-08-21T06:38:48","operations":[["account_create",{"fee":"0.000 GOLOS","creator":"cyberfounder","new_account_name":"vtsn","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS8DUuUETweg3f3YN6VypNKFTcxZ9uFqxVi6x2TuGaPYg9eJF6VZ",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS74vRVnybySiuya1d3JBeUGEw6aw4pWwcUf5aaxajj4X2EJss2G",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS5W9jtsqhZUbvobKcpng8jicvwUBnDxjZjUyJ355GXDC7J75J9J",1]]},"memo_key":"GLS7C5ufZagDvWRJg9XTGF51VrENfqpRRFzhoUjnyFUc9nptGoMpf","json_metadata":""}]],"extensions":[],"signatures":["2017cc34a168cf669dbe916c6068f1aaecdc31248def2822565758538f9b8636b27fde91500f04471d85239c277e69c3fed9496e5c7c3144251ee8626f911ea065"]}]]}\n    th_a  websocket_api.cpp:124 on_message',
        data: [Object] } } } undefined

Спасибо

**Comment by b1acksun** [comment]
Скорее всего, ошибка связана с тем, что по умолчанию в golos-js  `chain-id = 782a3039b478c839e4cb0c941ff4eaeb7df40bdd68bd441afd444b9da763de12`, необходимо дополнительно настроить для работы с тестнетом `golos.config.set('chain_id','5876894a41e6361bde2e73278f07340f2eb8b41c2facd29099de9deef6cdb679');`

**Comment by votason** [comment]
Спасибо огромное за подсказку, как то упустил, все получилось.
