### ISSUE TITLE
get_trending_categories was losted

### ISSUE THREAD

**Issue by t3ran13** [GolosChain/golos-js#47]
изчез метод get_trending_categories в 0.7 версии для 18 ХФ

**Comment by b1acksun** [comment]
Метод был удален, согласно [изменениям в API](https://wiki.golos.io/golosd/HardFork/New_HardFork-HF18.html#%D0%B8%D0%B7%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F-%D0%B2-%D0%BF%D0%BB%D0%B0%D0%B3%D0%B8%D0%BD%D0%B5-socialnetwork)
