### ISSUE TITLE
Получение getFollowers/getFollowing с оффсетом от заданного аккаунта

### ISSUE THREAD

**Issue by beautyfree** [GolosChain/golos-js#53]
**Проблема:**
При вызове getFollowersAsync со startFollower='', golos-js вместо пустой строки отправляет то что было использовано в предыдущий вызов getFollowersAsync.

**Воспроизведение:**
1. getFollowers('golosio', 'devall', followType, limit)
2. getFollowers('golosio', '', followType, limit)

**Результат:** во втором случае вместо пустой строки отправляется 'devall'
**Ожидаемый результат:** отправляется пустая строка

**Comment by b1acksun** [comment]
https://github.com/GolosChain/golos-js/commit/79f0813210985dd4b5c5d0291d0c335442ebf13f
