### ISSUE TITLE
Не работает отправка транзакции c коллбэком

### ISSUE THREAD

**Issue by gropox** [GolosChain/golos-js#56]
https://github.com/GolosChain/golos-js/blob/0.7.4/src/broadcast/index.js#L42

Первым параметром передается колбэк функция ,которая больше не поддерживается API. В результате, если выполнить перед отправкой 

golos.config.set("broadcast_transaction_with_callback", true)

попытка отправить транзакцию результируется в

```
Unhandled rejection Error: Invalid parameter value (1020400)
Invalid value "" for parameter "trx": Bad Cast (7)
```

**Comment by b1acksun** [comment]
Какая версия ноды?

**Comment by gropox** [comment]
Я пробовал с публичной нодой, golos.io. Возможно 18.6

**Comment by b1acksun** [comment]
Проверил на ноде версии 19 - колбек отрабатывает
