### ISSUE TITLE
get_ticker метод в methods.json определен без параметров

### ISSUE THREAD

**Issue by gropox** [GolosChain/golos-js#6]
*get_ticker* метод в methods.json определен без параметров, хотя API вызов требует 2 параметра. base и  quote

Пример вызова из GUI

`message: {"id":0,"method":"call","params":[6,"get_ticker",["GOLOS","GBG"]]}`

Определение в исходниках v0.17

`market_ticker get_ticker(const string &base, const string &quote) const;`

**Comment by b1acksun** [comment]
https://github.com/GolosChain/golos-js/blob/master/src/api/methods.js#L510

**Comment by gropox** [comment]
Сорри, глядел, ту что в репозитори npm-а. А библиотека как то версионируется?  Что бы взять и установить конкретно под 0.17?

**Comment by b1acksun** [comment]
Для 0.17 можно установить последнюю версию (0.5.26) c [npm](https://www.npmjs.com/package/golos-js)
