### ISSUE TITLE
Список событий голоса

### ISSUE THREAD

**Issue by votason** [GolosChain/golos-js#9]
Добрый день!

Где можно поднять информацию о событиях голоса, точнее сказать именно список событий для обработки этой информации ?

vote
comment
transfer
custom_json - ???
pow2 - ???
transfer_to_vesting
convert - ???
feed_publish - ???
limit_order_create - ???
comment_options - ???

Спасибо.

**Comment by b1acksun** [comment]
> The solution is to parse blockchain and get the data required from the set of blocks.
[Nemo1369](https://github.com/GolosChain/golos/issues/202)
